# Generated by Django 4.2.24 on 2025-09-30 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Product name must be unique', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed product description')),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current stock quantity (cannot be negative)', validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Threshold below which product is considered low stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is active in inventory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
